---
- name: Delete a cloud function
  block:
    - name: Delete a cloud function
      google.cloud.gcp_cloudfunctions_cloud_function:
        name: "{{ func_name }}"
        location: "{{ func_location }}"
        project: "{{ func_project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ service_account_file }}"
        state: absent
      # noqa: var-naming[no-role-prefix]
      register: delete_result

    - name: Print result
      ansible.builtin.debug:
        # noqa: var-naming[no-role-prefix]
        msg: "Deleted function {{ func_name }}: {{ delete_result.changed }}"
